language: node_js
node_js:
  - '0.8'
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
# inside a repository with .travis.yml
travis-lint

# from any directory
travis-lint client/.travis.yml